import { NextRequest, NextResponse } from 'next/server';

// Secure download endpoint with one-time use tokens
// In production, this would:
// 1. Verify the charge was paid
// 2. Check if the token is still valid
// 3. Serve the prompt file from storage

interface DownloadParams {
  params: Promise<{ chargeId: string }>;
}

export async function GET(
  request: NextRequest,
  { params }: DownloadParams
) {
  try {
    const { chargeId } = await params;

    // Mock: In production, verify payment was confirmed
    // const { data: order, error } = await supabase
    //   .from('orders')
    //   .select('*')
    //   .eq('coinbase_checkout_id', chargeId)
    //   .eq('status', 'confirmed')
    //   .single();

    // if (error || !order) {
    //   return NextResponse.json(
    //     { error: 'Invalid download link' },
    //     { status: 401 }
    //   );
    // }

    console.log('[DOWNLOAD] File requested for charge:', chargeId);

    // Mock: In production, fetch file from Vercel Blob Storage
    // const fileUrl = await blob.download(order.prompt_id);

    // Mock file content
    const promptContent = `
# Social Media Content Machine

You are an expert social media strategist with years of experience managing viral accounts.

## Your Task
Create a 30-day social media content calendar optimized for maximum engagement and reach.

## Instructions
1. Understand the niche and target audience
2. Generate diverse content types (educational, entertaining, promotional)
3. Include specific hashtag strategies
4. Provide caption templates
5. Optimize for each platform's algorithm

## Output Format
Provide the calendar as:
- Date
- Content type
- Topic
- Platform(s)
- Key hooks
- Call-to-action
- Hashtags

## Pricing
This prompt is ready to use. Copy it directly into ChatGPT, Claude, or any other AI.

---
Generated by PromptDeal
Purchased on: ${new Date().toISOString()}
`;

    // Return file as download
    return new NextResponse(promptContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': 'attachment; filename="prompt.txt"',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
      },
    });
  } catch (error) {
    console.error('[DOWNLOAD] Error:', error);
    return NextResponse.json(
      { error: 'Download failed' },
      { status: 500 }
    );
  }
}
